notification-service.uriport=8085
notification-service.datasource-url=jdbc:mysql://localhost:3306/notification_service_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
notification-service.username=root
notification-service.password=root
notification-service.hibernate-ddl-auto=update
notification-service.showsql=true
notification-service.urlregistry=http://localhost:8761/eureka/
notification-service.rabbitmq-host=localhost
notification-service.seuil.solde-faible=500