notification-service.uriport=8085

notification-service.datasource-url=jdbc:mysql://localhost:3306/notification_service_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
notification-service.username=root
notification-service.password=
notification-service.hibernate-ddl-auto=update
notification-service.showsql=true

notification-service.urlregistry=http://localhost:8761/eureka/
notification-service.rabbitmq-host=localhost

# Seuil alerte solde faible (FCFA)
notification-service.seuil.solde-faible=500

# =============================================
# RABBITMQ - mêmes valeurs que Trip Service
# =============================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.exchange.name=smart-mobility-exchange
rabbitmq.queue.trip-completed=trip.completed.queue
rabbitmq.queue.pricing-fallback=pricing.fallback.queue
rabbitmq.routing-key.trip-completed=trip.completed
rabbitmq.routing-key.pricing-fallback=pricing.fallback.used

# =============================================
# ZIPKIN
# =============================================
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# =============================================
# ACTUATOR
# =============================================
management.endpoints.web.exposure.include=health,info,metrics,refresh
management.endpoint.health.show-details=always

# =============================================
# LOGS
# =============================================
logging.level.com.smartmobility=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}/%X{spanId}] %-5level %logger{36} - %msg%n
logging.level.org.springframework.amqp=DEBUG