server.port=8888
spring.cloud.config.server.git.uri=https://github.com/TURKEYSTAR/smart-mobility-config-repo
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.search-paths=spring-cloud-server-config,eureka-registry-server,api-gateway,user-service,trip-service,pricing-service,billing-service,notification-service
spring.cloud.config.server.git.clone-on-start=true

# Ne pas s'enregistrer dans Eureka
eureka.client.enabled=false