auth-service.uriport=8086

jwt.secret=smart-mobility-pass-secret-key-256-bits-minimum-requis
jwt.expiration=86400000

# ── OAuth2 Google ───
google.client-id=REMPLACER_PAR_TON_CLIENT_ID
google.client-secret=REMPLACER_PAR_TON_CLIENT_SECRET