pricing-service.uriport=8083
pricing-service.datasource-url=jdbc:mysql://localhost:3306/pricing_service_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
pricing-service.username=root
pricing-service.password=root
pricing-service.hibernate-ddl-auto=update
pricing-service.showsql=true
pricing-service.urlregistry=http://localhost:8761/eureka/

# Règles tarifaires
pricing-service.tarif.bus=200
pricing-service.tarif.brt=350
pricing-service.tarif.ter=500
pricing-service.reduction.heures-creuses=0.20
pricing-service.reduction.fidelite=0.10
pricing-service.reduction.abonnement=0.15
pricing-service.plafond.journalier=2000