trip-service.uriport=8082
trip-service.datasource-url=jdbc:mysql://localhost:3306/trip_service_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
trip-service.username=root
trip-service.password=root
trip-service.hibernate-ddl-auto=update
trip-service.showsql=true
trip-service.urlregistry=http://localhost:8761/eureka/