eureka-registry-naming-server.uriport=8761
eureka-registry-naming-server.fetchregistry=false

eureka.client.register-with-eureka=false
eureka.server.enable-self-preservation=true
eureka.instance.hostname=eureka-server