eureka-registry-naming-server.uriport=8761
eureka-registry-naming-server.fetchregistry=false

eureka.client.register-with-eureka=false
eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.instance.hostname=localhost