billing-service.uriport=8084
billing-service.datasource-url=jdbc:mysql://localhost:3306/billing_service_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
billing-service.username=root
billing-service.password=root
billing-service.hibernate-ddl-auto=update
billing-service.showsql=true
billing-service.urlregistry=http://localhost:8761/eureka/